import mongoose from "mongoose";

const algorithmProfileSchema = new mongoose.Schema(
  {
    selectedInterests: { type: [String], default: [] },
    interestWeights: { type: Map, of: Number, default: {} },
    negativeInterestWeights: { type: Map, of: Number, default: {} },
    preferredLanguages: { type: [String], default: [] },
    nativeLanguage: { type: String, default: "" },
    learningLanguages: { type: [String], default: [] },
    contentPreferences: {
      memes: { type: Boolean, default: true },
      gaming: { type: Boolean, default: true },
      coding: { type: Boolean, default: true },
      music: { type: Boolean, default: true },
      sports: { type: Boolean, default: true },
      languageLearning: { type: Boolean, default: true },
      news: { type: Boolean, default: false },
      politics: { type: Boolean, default: false },
    },
    feedMode: { type: String, default: "balanced" },
    mutedHashtags: { type: [String], default: [] },
    hiddenPosts: { type: [String], default: [] },
    lastUpdatedAt: { type: Date, default: Date.now },
  },
  { _id: false }
);

const userSchema = new mongoose.Schema(
  {
    _id: { type: String, default: () => new mongoose.Types.ObjectId().toString() },
    fullName: { type: String, required: true, trim: true, maxlength: 80 },
    username: { type: String, required: true, unique: true, lowercase: true, trim: true, maxlength: 32 },
    email: { type: String, required: true, unique: true, lowercase: true, trim: true },
    password: { type: String, required: true },
    profilePic: { type: String, default: "" },
    bio: { type: String, default: "", maxlength: 240 },
    nativeLanguage: { type: String, default: "" },
    learningLanguage: { type: String, default: "" },
    learningLanguages: { type: [String], default: [] },
    location: { type: String, default: "" },
    isOnboarded: { type: Boolean, default: false },
    role: { type: String, enum: ["user", "mod", "admin", "creator"], default: "user", index: true },
    emailVerified: { type: Boolean, default: false },
    emailVerifiedAt: Date,
    followers: { type: [String], default: [], index: true },
    following: { type: [String], default: [], index: true },
    friends: { type: [String], default: [] },
    isPrivate: { type: Boolean, default: false },
    allowMessagesFrom: { type: String, enum: ["everyone", "followers", "friends", "nobody"], default: "everyone" },
    showFollowers: { type: Boolean, default: true },
    showFollowing: { type: Boolean, default: true },
    security: {
      emailCodeOnLogin: { type: Boolean, default: false },
      loginAlertsEnabled: { type: Boolean, default: true },
      trustedDeviceIds: { type: [String], default: [] },
    },
    interests: { type: [String], default: [] },
    mutedInterests: { type: [String], default: [] },
    blockedUsers: { type: [String], default: [] },
    mutedUsers: { type: [String], default: [] },
    mutedWords: { type: [String], default: [] },
    readReceiptsEnabled: { type: Boolean, default: true },
    isOnline: { type: Boolean, default: false },
    lastSeen: { type: Date, default: Date.now },
    inCall: { type: Boolean, default: false },
    cameraEnabled: { type: Boolean, default: true },
    micEnabled: { type: Boolean, default: true },
    bannedUntil: Date,
    banReason: { type: String, default: "" },
    banIssuedAt: Date,
    banDays: Number,
    fullBannedAt: Date,
    fullBanReason: { type: String, default: "" },
    fullBanBy: String,
    messageBanUntil: Date,
    messageBanReason: { type: String, default: "" },
    shadowBannedUntil: Date,
    shadowBanReason: { type: String, default: "" },
    moderationRecords: { type: [Object], default: [] },
    customBadges: { type: [String], default: [] },
    verifiedBadgeOverride: { type: Boolean, default: false },
    verifiedBadgeBlocked: { type: Boolean, default: false },
    algorithmProfile: { type: algorithmProfileSchema, default: () => ({}) },
  },
  { timestamps: true, strict: false }
);

export default mongoose.models.User || mongoose.model("User", userSchema);
